export const allPhotos = [
  // === Murale ===
  { index: 1, src: "/Portfolio/murale/1.webp", title: "Mural artystyczny", category: "Murale", width: 2400, height: 1920 },
  { index: 2, src: "/Portfolio/murale/2.webp", title: "Mural dekoracyjny", category: "Murale", width: 3382, height: 2000 },
  { index: 3, src: "/Portfolio/murale/3.webp", title: "Mural panoramiczny", category: "Murale", width: 2400, height: 1201 },
  { index: 4, src: "/Portfolio/murale/4.webp", title: "Mural panorama", category: "Murale", width: 2400, height: 500 },
  { index: 5, src: "/Portfolio/murale/5a.webp", title: "Mural wielkoformatowy", category: "Murale", width: 2400, height: 937 },
  { index: 6, src: "/Portfolio/murale/6.webp", title: "Mural kwadratowy", category: "Murale", width: 2571, height: 2500 },
  { index: 7, src: "/Portfolio/murale/7A.webp", title: "Mural miejski", category: "Murale", width: 2400, height: 1344 },
  { index: 8, src: "/Portfolio/murale/7B.webp", title: "Mural szeroki", category: "Murale", width: 2400, height: 426 },
  { index: 9, src: "/Portfolio/murale/7c.webp", title: "Mural kolorowy", category: "Murale", width: 2400, height: 1651 },
  { index: 10, src: "/Portfolio/murale/8.webp", title: "Mural krajobrazowy", category: "Murale", width: 2400, height: 1157 },
  { index: 11, src: "/Portfolio/murale/9.webp", title: "Mural pionowy", category: "Murale", width: 2215, height: 3909 },
  { index: 12, src: "/Portfolio/murale/10.webp", title: "Mural detaliczny", category: "Murale", width: 3293, height: 2500 },
  { index: 13, src: "/Portfolio/murale/12.webp", title: "Mural fasadowy", category: "Murale", width: 2400, height: 1314 },
  { index: 14, src: "/Portfolio/murale/13.webp", title: "Mural szeroki 2", category: "Murale", width: 2400, height: 949 },
  { index: 15, src: "/Portfolio/murale/1c.webp", title: "Mural portretowy", category: "Murale", width: 2000, height: 2648 },
  { index: 16, src: "/Portfolio/murale/2Az.webp", title: "Mural artystyczny 2", category: "Murale", width: 2661, height: 1921 },
  { index: 17, src: "/Portfolio/murale/3cropped.webp", title: "Mural przycięty", category: "Murale", width: 2400, height: 888 },

  // === Wnętrza ===
  { index: 19, src: "/Portfolio/wnetrza/w1a.webp", title: "Wnętrze panorama", category: "Wnętrza", width: 4000, height: 1947 },
  { index: 20, src: "/Portfolio/wnetrza/w1b.webp", title: "Dekoracja wnętrza", category: "Wnętrza", width: 3732, height: 2000 },
  { index: 21, src: "/Portfolio/wnetrza/w1c.webp", title: "Malowidło ścienne", category: "Wnętrza", width: 3584, height: 3452 },
  { index: 22, src: "/Portfolio/wnetrza/w2.webp", title: "Wnętrze szerokie", category: "Wnętrza", width: 3429, height: 2000 },
  { index: 23, src: "/Portfolio/wnetrza/w3.webp", title: "Mural wewnętrzny", category: "Wnętrza", width: 2400, height: 1474 },
  { index: 24, src: "/Portfolio/wnetrza/w4.webp", title: "Panorama wnętrza", category: "Wnętrza", width: 5272, height: 2956 },
  { index: 25, src: "/Portfolio/wnetrza/w4a.webp", title: "Pokój portret", category: "Wnętrza", width: 2094, height: 2177 },
  { index: 26, src: "/Portfolio/wnetrza/w6.webp", title: "Dekoracja kwadrat", category: "Wnętrza", width: 1080, height: 1080 },
  { index: 27, src: "/Portfolio/wnetrza/w7.webp", title: "Pokój dziecięcy", category: "Wnętrza", width: 1080, height: 1350 },
  { index: 28, src: "/Portfolio/wnetrza/w8.webp", title: "Artystyczne wnętrze", category: "Wnętrza", width: 2400, height: 1713 },
  { index: 29, src: "/Portfolio/wnetrza/w9a.webp", title: "Wnętrze dekoracja", category: "Wnętrza", width: 2500, height: 2090 },
  { index: 30, src: "/Portfolio/wnetrza/w10.webp", title: "Wnętrze kolorowe", category: "Wnętrza", width: 2400, height: 1589 },
  { index: 31, src: "/Portfolio/wnetrza/w11.webp", title: "Dekoracja ścienna", category: "Wnętrza", width: 2400, height: 1621 },
  { index: 32, src: "/Portfolio/wnetrza/w12.webp", title: "Detal wnętrza", category: "Wnętrza", width: 1346, height: 986 },
  { index: 33, src: "/Portfolio/wnetrza/w13.webp", title: "Wnętrze finalne", category: "Wnętrza", width: 2000, height: 1238 },
  { index: 34, src: "/Portfolio/wnetrza/ww3.webp", title: "Wnętrze malowane", category: "Wnętrza", width: 2400, height: 1493 },
  { index: 35, src: "/Portfolio/wnetrza/P1371888.webp", title: "Malowidło P1", category: "Wnętrza", width: 2302, height: 3004 },
  { index: 36, src: "/Portfolio/wnetrza/P1371890.webp", title: "Malowidło P2", category: "Wnętrza", width: 2400, height: 1751 },
  { index: 37, src: "/Portfolio/wnetrza/P1371966.webp", title: "Malowidło P3", category: "Wnętrza", width: 4057, height: 5071 },
  { index: 38, src: "/Portfolio/wnetrza/P1371980.webp", title: "Malowidło P4", category: "Wnętrza", width: 4098, height: 4098 },

  // === Ptasia galeria ===
  { index: 39, src: "/Portfolio/ptasie/1.webp", title: "Ptak panorama", category: "Ptasia galeria", width: 2400, height: 1168 },
  { index: 40, src: "/Portfolio/ptasie/2.webp", title: "Ptak kwadrat", category: "Ptasia galeria", width: 2400, height: 2400 },
  { index: 41, src: "/Portfolio/ptasie/3.webp", title: "Ptak szeroki", category: "Ptasia galeria", width: 2400, height: 1351 },
  { index: 42, src: "/Portfolio/ptasie/3a.webp", title: "Ptaki panorama", category: "Ptasia galeria", width: 2400, height: 500 },
  { index: 43, src: "/Portfolio/ptasie/3b.webp", title: "Ptak kolorowy", category: "Ptasia galeria", width: 2400, height: 1600 },
  { index: 44, src: "/Portfolio/ptasie/5.webp", title: "Ptak pionowy", category: "Ptasia galeria", width: 2400, height: 2314 },
  { index: 45, src: "/Portfolio/ptasie/5d.webp", title: "Ptak portret", category: "Ptasia galeria", width: 1774, height: 2400 },
  { index: 46, src: "/Portfolio/ptasie/6c.webp", title: "Ptak detal", category: "Ptasia galeria", width: 1855, height: 2400 },
  { index: 47, src: "/Portfolio/ptasie/6d.webp", title: "Ptak mural", category: "Ptasia galeria", width: 1920, height: 2400 },
  { index: 48, src: "/Portfolio/ptasie/7.webp", title: "Ptak krajobraz", category: "Ptasia galeria", width: 2400, height: 1485 },
  { index: 49, src: "/Portfolio/ptasie/7b.webp", title: "Ptak szeroki 2", category: "Ptasia galeria", width: 2400, height: 1648 },
  { index: 50, src: "/Portfolio/ptasie/8.webp", title: "Ptak wysoki", category: "Ptasia galeria", width: 1920, height: 2400 },
  { index: 51, src: "/Portfolio/ptasie/8bs.webp", title: "Ptak wysoki 2", category: "Ptasia galeria", width: 1920, height: 2400 },
  { index: 52, src: "/Portfolio/ptasie/9.webp", title: "Ptak portret 2", category: "Ptasia galeria", width: 1766, height: 2400 },
  { index: 53, src: "/Portfolio/ptasie/10.webp", title: "Ptak krajobraz 2", category: "Ptasia galeria", width: 2400, height: 1636 },
  { index: 54, src: "/Portfolio/ptasie/10a.webp", title: "Ptak pionowy 2", category: "Ptasia galeria", width: 1995, height: 2131 },
  { index: 55, src: "/Portfolio/ptasie/11s.webp", title: "Ptak finałowy", category: "Ptasia galeria", width: 2400, height: 1870 },
  { index: 56, src: "/Portfolio/ptasie/finish-1a.webp", title: "Ptak finish", category: "Ptasia galeria", width: 2400, height: 1436 },

  // === Branding ===
  { index: 57, src: "/Portfolio/Brending/przedszkole 1v.webp", title: "Przedszkole", category: "Branding", width: 4000, height: 1876 },
  { index: 58, src: "/Portfolio/Brending/grafika 4.webp", title: "Grafika pionowa", category: "Branding", width: 1961, height: 3000 },
  { index: 59, src: "/Portfolio/Brending/grafika 6a.webp", title: "Grafika wielkoformatowa", category: "Branding", width: 2400, height: 1388 },
  { index: 60, src: "/Portfolio/Brending/grafika 7.webp", title: "Branding projekt", category: "Branding", width: 2400, height: 1577 },
  { index: 61, src: "/Portfolio/Brending/grafika 8.webp", title: "Logo", category: "Branding", width: 1080, height: 898 },
  { index: 62, src: "/Portfolio/Brending/tif 2d.webp", title: "Projekt 2D", category: "Branding", width: 2400, height: 1533 },
  { index: 63, src: "/Portfolio/Brending/w2.webp", title: "Grafika naścienna", category: "Branding", width: 2400, height: 2062 },
];

export const portfolioPhotos = [
  {
    index: 1,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/7b.webp",
    title: "Mural panoramiczny",
    category: "Murale",
    width: 2400,
    height: 426,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 10,
    rowspan: 1,
    gridArea: "photo1",
  },
  {
    index: 2,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/3cropped.webp",
    title: "Mural wielkoformatowy",
    category: "Murale",
    width: 2400,
    height: 888,
    smcolspan: 4,
    smrowspan: 1,
    colspan: 5,
    rowspan: 1,
    gridArea: "photo2",
  },
  {
    index: 4,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/1.webp",
    title: "Mural artystyczny",
    category: "Murale",
    width: 2400,
    height: 1920,
    smcolspan: 4,
    smrowspan: 3,
    colspan: 5,
    rowspan: 2,
    gridArea: "photo4",
  },
  {
    index: 5,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/9.webp",
    title: "Mural pionowy",
    category: "Murale",
    width: 1360,
    height: 2400,
    smcolspan: 4,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2,
    gridArea: "photo5",
  },
  {
    index: 6,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/8.webp",
    title: "Mural krajobrazowy",
    category: "Murale",
    width: 2400,
    height: 1157,
    smcolspan: 7,
    smrowspan: 2,
    colspan: 5,
    rowspan: 2,
    gridArea: "photo6",
    compound: [
      {
        src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/8.webp",
        title: "Mural krajobrazowy",
        width: 2400,
        height: 1157,
      },
      {
        src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/10.webp",
        title: "Mural detaliczny",
        width: 3293,
        height: 2500,
      },
    ],
    compoundRatio: "1fr 1fr",
  },
  {
    index: 7,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/4.webp",
    title: "Mural miejski",
    category: "Murale",
    width: 2400,
    height: 500,
    smcolspan: 10,
    smrowspan: 2,
    colspan: 7,
    rowspan: 2,
    gridArea: "photo7",
    objectFit: "contain",
    objectPosition: "center top",
  },
  {
    index: 8,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/2.webp",
    title: "Mural kolorowy",
    category: "Murale",
    width: 3382,
    height: 2000,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 3,
    rowspan: 1,
    gridArea: "photo8",
  },
  {
    index: 9,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/10.webp",
    title: "Mural detaliczny",
    category: "Murale",
    width: 3293,
    height: 2500,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2,
    gridArea: "photo9",
    objectPosition: "center 20%",
  },
  {
    index: 10,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/8.webp",
    title: "Mural szeroki",
    category: "Murale",
    width: 2400,
    height: 1157,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2,
    gridArea: "photo10",
    objectPosition: "center 35%",
  },
  {
    index: 11,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/4.webp",
    title: "Mural panorama",
    category: "Murale",
    width: 2400,
    height: 500,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2,
    gridArea: "photo11",
  },
];

export const komunikacjaWizualnaPhotos = [
  { index: 1, src: "/Animation/Komunikacja_Wizualna/PortfolioCard/przedszkole-1v.webp", title: "Przedszkole", category: "Komunikacja Wizualna", width: 2400, height: 1126, smcolspan: 10, smrowspan: 1, colspan: 5, rowspan: 1, gridArea: "photo1" },
  { index: 2, src: "/Animation/Komunikacja_Wizualna/PortfolioCard/w2.webp", title: "Grafika naścienna", category: "Komunikacja Wizualna", width: 2400, height: 2062, smcolspan: 4, smrowspan: 1, colspan: 3, rowspan: 2, gridArea: "photo2" },
  { index: 3, src: "/Animation/Komunikacja_Wizualna/PortfolioCard/grafika-4.webp", title: "Szyld pionowy", category: "Komunikacja Wizualna", width: 1569, height: 2400, smcolspan: 6, smrowspan: 1, colspan: 2, rowspan: 3, gridArea: "photo3" },
  { index: 4, src: "/Animation/Komunikacja_Wizualna/PortfolioCard/grafika-7.webp", title: "Branding", category: "Komunikacja Wizualna", width: 2400, height: 1577, smcolspan: 4, smrowspan: 3, colspan: 3, rowspan: 2, gridArea: "photo4" },
  { index: 5, src: "/Animation/Komunikacja_Wizualna/PortfolioCard/grafika-6a.webp", title: "Grafika wielkoformatowa", category: "Komunikacja Wizualna", width: 2400, height: 1388, smcolspan: 4, smrowspan: 1, colspan: 3, rowspan: 1, gridArea: "photo5", objectPosition: "left center", tabletObjectPosition: "center", mobileObjectPosition: "center" },
  { index: 6, src: "/Animation/Komunikacja_Wizualna/PortfolioCard/tif-2d.webp", title: "Projekt 2D", category: "Komunikacja Wizualna", width: 2400, height: 1533, smcolspan: 5, smrowspan: 2, colspan: 3, rowspan: 1, gridArea: "photo6", tabletObjectPosition: "30% center", mobileObjectPosition: "right center" },
];

export const wnetrzaPhotos = [
  { index: 1, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/w1a.webp", title: "Wnętrze panorama", category: "Wnętrza", width: 2400, height: 1168, smcolspan: 10, smrowspan: 1, colspan: 10, rowspan: 1, gridArea: "photo1" },
  { index: 2, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/p1371980.webp", title: "Dekoracja kwadrat", category: "Wnętrza", width: 2400, height: 2400, smcolspan: 4, smrowspan: 1, colspan: 5, rowspan: 1, gridArea: "photo2" },
  { index: 3, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/p1371888.webp", title: "Malowidło ścienne", category: "Wnętrza", width: 1839, height: 2400, smcolspan: 6, smrowspan: 1, colspan: 5, rowspan: 1, gridArea: "photo3", tabletObjectPosition: "30% center", mobileObjectPosition: "30% center" },
  { index: 4, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/w1c.webp", title: "Dekoracja wnętrza", category: "Wnętrza", width: 2400, height: 2312, smcolspan: 4, smrowspan: 3, colspan: 5, rowspan: 2, gridArea: "photo4", tabletObjectPosition: "center top", mobileObjectPosition: "center top" },
  { index: 6, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/w3.webp", title: "Mural wewnętrzny", category: "Wnętrza", width: 2400, height: 1474, smcolspan: 7, smrowspan: 2, colspan: 5, rowspan: 1, gridArea: "photo6" },
  { index: 7, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/w8.webp", title: "Artystyczne wnętrze", category: "Wnętrza", width: 2400, height: 1713, smcolspan: 7, smrowspan: 2, colspan: 5, rowspan: 2, gridArea: "photo7" },
  { index: 8, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/w11.webp", title: "Dekoracja", category: "Wnętrza", width: 2400, height: 1621, smcolspan: 10, smrowspan: 1, colspan: 5, rowspan: 2, gridArea: "photo8" },
  { index: 9, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/w4a.webp", title: "Pokój portret", category: "Wnętrza", width: 2094, height: 2177, smcolspan: 6, smrowspan: 1, colspan: 3, rowspan: 2, gridArea: "photo9" },
  { index: 10, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/w2.webp", title: "Wnętrze szerokie", category: "Wnętrza", width: 2400, height: 1400, smcolspan: 6, smrowspan: 1, colspan: 3, rowspan: 2, gridArea: "photo10" },
  { index: 11, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/w4.webp", title: "Panorama wnętrza", category: "Wnętrza", width: 2400, height: 1346, smcolspan: 6, smrowspan: 1, colspan: 3, rowspan: 2, gridArea: "photo11" },
];

export const projektySpecjalnePhotos = [
  { index: 1, src: "/Animation/Projekty_Specjalne/PortfolioCard/samochodzik-7a.webp", title: "Samochodzik portret", category: "Projekty Specjalne", width: 1916, height: 2400, gridArea: "photo1" },
  { index: 2, src: "/Animation/Projekty_Specjalne/PortfolioCard/dscf4057a.webp", title: "Event artystyczny", category: "Projekty Specjalne", width: 2400, height: 1611, gridArea: "photo2", mobileObjectPosition: "right center" },
  { index: 3, src: "/Animation/Projekty_Specjalne/PortfolioCard/samochodzik-10.webp", title: "Malowanie samochodu", category: "Projekty Specjalne", width: 2400, height: 1565, gridArea: "photo3" },
  { index: 4, src: "/Animation/Projekty_Specjalne/PortfolioCard/samochodzik-11.webp", title: "Samochodzik", category: "Projekty Specjalne", width: 2400, height: 1592, gridArea: "photo4", objectPosition: "center 35%" },
  { index: 5, src: "/Animation/Projekty_Specjalne/PortfolioCard/samochodzik-3.webp", title: "Detal samochodu", category: "Projekty Specjalne", width: 2400, height: 1286, gridArea: "photo5" },
  { index: 6, src: "/Animation/Projekty_Specjalne/PortfolioCard/motyl-1a.webp", title: "Motyl", category: "Projekty Specjalne", width: 2400, height: 1539, gridArea: "photo6" },
  { index: 7, src: "/Animation/Projekty_Specjalne/PortfolioCard/samochodzik-12.webp", title: "Samochodzik finalny", category: "Projekty Specjalne", width: 2400, height: 1529, gridArea: "photo7" },
];