export const allPhotos = [
  {
    index: 27,
    src: "/images/komeko-mural.jpg",
    title: "komeko",
    category: "Murale",
    width: 9315,
    height: 2196,
    gridArea: "photo1",
  },
  {
    index: 26,
    src: "/images/motyl.jpg",
    title: "motyl",
    category: "Wnętrza",
    width: 4814,
    height: 3207,
    smcolspan: 4,
    smrowspan: 1,
    colspan: 5,
    rowspan: 1, // Adjusted for aspect ratio
    gridArea: "photo2",
  },
  {
    index: 25,
    src: "/Portfolio/mural-akwarium.jpg",
    title: "akwarium",
    category: "Wnętrza",
    width: 5776,
    height: 4314,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 5,
    rowspan: 1, // Adjusted for aspect ratio
    gridArea: "photo3",
  },
  {
    index: 24,
    src: "/images/lpec-dom1.jpg",
    title: "lpec",
    category: "Murale",
    width: 4337,
    height: 5776,
    smcolspan: 4,
    smrowspan: 3,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo4",
  },
  {
    index: 23,
    src: "/images/1b.jpg",
    title: "soldiers",
    category: "Murale",
    width: 5776,
    height: 4337,
    smcolspan: 4,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo5",
  },
  {
    index: 22,
    src: "/Portfolio/mural-spongebob.jpg",
    title: "stare miasto 2",
    category: "Murale",
    width: 4337,
    height: 5776,
    smcolspan: 3,
    smrowspan: 2,
    colspan: 2,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo6",
  },
  {
    index: 19,
    src: "/Portfolio/mural-stare-miasto.jpg",
    title: "stare miasto 2",
    category: "Murale",
    width: 5776,
    height: 4337,
    smcolspan: 7,
    smrowspan: 2,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo7",
  },
  {
    index: 18,
    src: "/images/sonic.jpg",
    title: "sonic",
    category: "Murale",
    width: 1080,
    height: 1080,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo8",
  },
  {
    index: 17,
    src: "/Portfolio/mural-stare-miasto-lublin.jpg",
    title: "staremiasto",
    category: "Murale",
    width: 4336,
    height: 5776,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo9",
  },
  {
    index: 16,
    src: "/images/6a.jpg",
    title: "lpec",
    category: "Murale",
    width: 4336,
    height: 5776,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo10",
  },
  {
    index: 15,
    src: "/images/magiczny-swiat.jpg",
    title: "staremiasto",
    category: "Murale",
    width: 2048,
    height: 1301,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 6,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo11",
  },
  {
    index: 14,
    src: "/images/s2a.jpg",
    title: "staremiasto",
    category: "Murale",
    width: 4336,
    height: 5776,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo12",
  },
  {
    index: 1,
    src: "/images/ptasie/4.webp",
    title: "komeko",
    category: "Murale",
    width: 3840,
    height: 960,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 10,
    rowspan: 1, // Adjusted for aspect ratio
    gridArea: "photo1",
  },
  {
    index: 2,
    src: "/images/ptasie/kogut1.webp",
    title: "szyld5",
    category: "Birds",
    width: 3868,
    height: 3730,
    smcolspan: 4,
    smrowspan: 1,
    colspan: 5,
    rowspan: 1, // Adjusted for aspect ratio
    gridArea: "photo2",
  },
  {
    index: 3,
    src: "/images/ptasie/CZAPLA3.webp",
    title: "akwarium",
    category: "Birds",
    width: 1080,
    height: 1350,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 5,
    rowspan: 1, // Adjusted for aspect ratio
    gridArea: "photo3",
  },
  {
    index: 4,
    src: "/images/ptasie/D5a.webp",
    title: "lpec",
    category: "Birds",
    width: 4337,
    height: 5776,
    smcolspan: 4,
    smrowspan: 3,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo4",
  },
  {
    index: 5,
    src: "/images/ptasie/3.webp",
    title: "soldiers",
    category: "Birds",
    width: 5776,
    height: 4337,
    smcolspan: 4,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo5",
  },
  {
    index: 6,
    src: "/images/ptasie/D1a.webp",
    title: "stare miasto 2",
    category: "Birds",
    width: 4337,
    height: 5776,
    smcolspan: 3,
    smrowspan: 2,
    colspan: 2,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo6",
  },
  {
    index: 7,
    src: "/images/ptasie/6d.webp",
    title: "stare miasto 2",
    category: "Birds",
    width: 5776,
    height: 4337,
    smcolspan: 7,
    smrowspan: 2,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo7",
  },
  {
    index: 8,
    src: "/images/ptasie/5.webp",
    title: "dogs",
    category: "Birds",
    width: 5776,
    height: 4337,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo8",
  },
  {
    index: 9,
    src: "/images/ptasie/6.webp",
    title: "dogs",
    category: "Birds",
    width: 5184,
    height: 3456,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo9",
  },
  {
    index: 10,
    src: "/images/ptasie/6d2.webp",
    title: "dogs",
    category: "Birds",
    width: 5032,
    height: 3456,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo10",
  },
  {
    index: 11,
    src: "/images/ptasie/finish1.webp",
    title: "dogs",
    category: "Birds",
    width: 5184,
    height: 3791,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo11",
  },
  {
    index: 12,
    src: "/images/ptasie/p1.webp",
    title: "bird-p1",
    category: "Birds",
    width: 5184,
    height: 3791,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo12",
  },
  {
    index: 13,
    src: "/images/s2a.jpg",
    title: "staremiasto",
    category: "Murale",
    width: 4336,
    height: 5776,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
  },
  {
    index: 27,
    src: "/images/camper.jpg",
    title: "Camper",
    category: "Samochody",
    width: 1914,
    height: 1220,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
  },
  {
    index: 28,
    src: "/images/camper2.jpg",
    title: "Camper2",
    category: "Samochody",
    width: 1904,
    height: 1263,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
  },
  {
    index: 28,
    src: "/images/camper3.jpg",
    title: "Camper3",
    category: "Samochody",
    width: 5076,
    height: 3368,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
  },
  {
    index: 29,
    src: "/images/c3.jpg",
    title: "C3",
    category: "Samochody",
    width: 4032,
    height: 3084,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
  },
];

export const portfolioPhotos = [
  {
    index: 1,
    src: "/images/komeko-mural.webp",
    title: "komeko",
    category: "Murale",
    width: 9315,
    height: 2196,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 10,
    rowspan: 1, // Adjusted for aspect ratio
    gridArea: "photo1",
  },
  {
    index: 2,
    src: "/images/motyl.jpg",
    title: "motyl",
    category: "Wnętrza",
    width: 4814,
    height: 3207,
    smcolspan: 4,
    smrowspan: 1,
    colspan: 5,
    rowspan: 1, // Adjusted for aspect ratio
    gridArea: "photo2",
  },
  {
    index: 3,
    src: "/Portfolio/mural-akwarium.jpg",
    title: "akwarium",
    category: "Wnętrza",
    width: 5776,
    height: 4314,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 5,
    rowspan: 1, // Adjusted for aspect ratio
    gridArea: "photo3",
  },
  {
    index: 4,
    src: "/images/lpec-dom1.jpg",
    title: "lpec",
    category: "Murale",
    width: 4337,
    height: 5776,
    smcolspan: 4,
    smrowspan: 3,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo4",
  },
  {
    index: 5,
    src: "/images/1b.jpg",
    title: "soldiers",
    category: "Murale",
    width: 5456,
    height: 3002,
    smcolspan: 4,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo5",
  },
  {
    index: 6,
    src: "/Portfolio/mural-spongebob.jpg",
    title: "stare miasto 2",
    category: "Murale",
    width: 4337,
    height: 5776,
    smcolspan: 3,
    smrowspan: 2,
    colspan: 2,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo6",
  },
  {
    index: 7,
    src: "/Portfolio/mural-stare-miasto.jpg",
    title: "stare miasto 2",
    category: "Murale",
    width: 5776,
    height: 4337,
    smcolspan: 7,
    smrowspan: 2,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo7",
  },
  {
    index: 8,
    src: "/images/sonic.jpg",
    title: "sonic",
    category: "Murale",
    width: 1080,
    height: 1080,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo8",
  },
  {
    index: 9,
    src: "/Portfolio/mural-stare-miasto-lublin.jpg",
    title: "staremiasto",
    category: "Murale",
    width: 4336,
    height: 5776,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo9",
  },
  {
    index: 10,
    src: "/images/6a.jpg",
    title: "lpec",
    category: "Murale",
    width: 4336,
    height: 5776,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo10",
  },
  {
    index: 11,
    src: "/images/magiczny-swiat.jpg",
    title: "staremiasto",
    category: "Murale",
    width: 4336,
    height: 5776,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo11",
  },
  {
    index: 12,
    src: "/images/s2a.jpg",
    title: "staremiasto",
    category: "Murale",
    width: 4336,
    height: 5776,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo12",
  },
];

export const PtasieMurale = [
  {
    index: 1,
    src: "/images/ptasie/4.webp",
    title: "komeko",
    category: "Murale",
    width: 3840,
    height: 960,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 10,
    rowspan: 1, // Adjusted for aspect ratio
    gridArea: "photo1",
  },
  {
    index: 2,
    src: "/images/ptasie/kogut1.webp",
    title: "szyld5",
    category: "Wnętrza",
    width: 3868,
    height: 3730,
    smcolspan: 4,
    smrowspan: 1,
    colspan: 5,
    rowspan: 1, // Adjusted for aspect ratio
    gridArea: "photo2",
  },
  {
    index: 3,
    src: "/images/ptasie/CZAPLA3.webp",
    title: "akwarium",
    category: "Wnętrza",
    width: 1080,
    height: 1350,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 5,
    rowspan: 1, // Adjusted for aspect ratio
    gridArea: "photo3",
  },
  {
    index: 4,
    src: "/images/ptasie/D5a.webp",
    title: "lpec",
    category: "Murale",
    width: 4337,
    height: 5776,
    smcolspan: 4,
    smrowspan: 3,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo4",
  },
  {
    index: 5,
    src: "/images/ptasie/3.webp",
    title: "soldiers",
    category: "Murale",
    width: 5776,
    height: 4337,
    smcolspan: 4,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo5",
  },
  {
    index: 6,
    src: "/images/ptasie/D1a.webp",
    title: "stare miasto 2",
    category: "Murale",
    width: 4337,
    height: 5776,
    smcolspan: 3,
    smrowspan: 2,
    colspan: 2,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo6",
  },
  {
    index: 7,
    src: "/images/ptasie/6d.webp",
    title: "stare miasto 2",
    category: "Murale",
    width: 5776,
    height: 4337,
    smcolspan: 7,
    smrowspan: 2,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo7",
  },
  {
    index: 8,
    src: "/images/ptasie/5.webp",
    title: "dogs",
    category: "Murale",
    width: 5776,
    height: 4337,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo8",
  },
  {
    index: 9,
    src: "/images/ptasie/6.webp",
    title: "dogs",
    category: "Murale",
    width: 5184,
    height: 3456,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo9",
  },
  {
    index: 10,
    src: "/images/ptasie/6d2.webp",
    title: "dogs",
    category: "Murale",
    width: 5032,
    height: 3456,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo10",
  },
  {
    index: 11,
    src: "/images/ptasie/finish1.webp",
    title: "dogs",
    category: "Murale",
    width: 5184,
    height: 3791,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo11",
  },
  {
    index: 12,
    src: "/images/ptasie/p1.webp",
    title: "dogs",
    category: "Murale",
    width: 5184,
    height: 3791,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo12",
  }
];