export const allPhotos = [
  {
    index: 27,
    src: "/images/komeko-mural.webp",
    title: "komeko",
    category: "Murale",
    width: 9315,
    height: 2196,
    gridArea: "photo1",
  },
  {
    index: 26,
    src: "/images/motyl.webp",
    title: "motyl",
    category: "Wnętrza",
    width: 4814,
    height: 3207,
    smcolspan: 4,
    smrowspan: 1,
    colspan: 5,
    rowspan: 1, // Adjusted for aspect ratio
    gridArea: "photo2",
  },
  {
    index: 25,
    src: "/Portfolio/mural-akwarium.webp",
    title: "akwarium",
    category: "Wnętrza",
    width: 5776,
    height: 4314,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 5,
    rowspan: 1, // Adjusted for aspect ratio
    gridArea: "photo3",
  },
  {
    index: 24,
    src: "/images/lpec-dom1.webp",
    title: "lpec",
    category: "Murale",
    width: 4337,
    height: 5776,
    smcolspan: 4,
    smrowspan: 3,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo4",
  },
  {
    index: 23,
    src: "/images/1b.webp",
    title: "soldiers",
    category: "Murale",
    width: 5776,
    height: 4337,
    smcolspan: 4,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo5",
  },
  {
    index: 22,
    src: "/Portfolio/mural-spongebob.webp",
    title: "stare miasto 2",
    category: "Murale",
    width: 4337,
    height: 5776,
    smcolspan: 3,
    smrowspan: 2,
    colspan: 2,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo6",
  },
  {
    index: 19,
    src: "/Portfolio/mural-stare-miasto.webp",
    title: "stare miasto 2",
    category: "Murale",
    width: 5776,
    height: 4337,
    smcolspan: 7,
    smrowspan: 2,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo7",
  },
  {
    index: 18,
    src: "/images/sonic.webp",
    title: "sonic",
    category: "Murale",
    width: 1080,
    height: 1080,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo8",
  },
  {
    index: 17,
    src: "/Portfolio/mural-stare-miasto-lublin.webp",
    title: "staremiasto",
    category: "Murale",
    width: 4336,
    height: 5776,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo9",
  },
  {
    index: 16,
    src: "/images/6a.webp",
    title: "lpec",
    category: "Murale",
    width: 4336,
    height: 5776,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo10",
  },
  {
    index: 15,
    src: "/images/magiczny-swiat.webp",
    title: "staremiasto",
    category: "Murale",
    width: 2048,
    height: 1301,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 6,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo11",
  },
  {
    index: 14,
    src: "/images/s2a.webp",
    title: "staremiasto",
    category: "Murale",
    width: 4336,
    height: 5776,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo12",
  },
  {
    index: 1,
    src: "/images/ptasie/4.webp",
    title: "komeko",
    category: "Murale",
    width: 3840,
    height: 960,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 10,
    rowspan: 1, // Adjusted for aspect ratio
    gridArea: "photo1",
  },
  {
    index: 2,
    src: "/images/ptasie/kogut1.webp",
    title: "szyld5",
    category: "Birds",
    width: 3868,
    height: 3730,
    smcolspan: 4,
    smrowspan: 1,
    colspan: 5,
    rowspan: 1, // Adjusted for aspect ratio
    gridArea: "photo2",
  },
  {
    index: 3,
    src: "/images/ptasie/CZAPLA3.webp",
    title: "akwarium",
    category: "Birds",
    width: 1080,
    height: 1350,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 5,
    rowspan: 1, // Adjusted for aspect ratio
    gridArea: "photo3",
  },
  {
    index: 4,
    src: "/images/ptasie/D5a.webp",
    title: "lpec",
    category: "Birds",
    width: 4337,
    height: 5776,
    smcolspan: 4,
    smrowspan: 3,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo4",
  },
  {
    index: 5,
    src: "/images/ptasie/3.webp",
    title: "soldiers",
    category: "Birds",
    width: 5776,
    height: 4337,
    smcolspan: 4,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo5",
  },
  {
    index: 6,
    src: "/images/ptasie/D1a.webp",
    title: "stare miasto 2",
    category: "Birds",
    width: 4337,
    height: 5776,
    smcolspan: 3,
    smrowspan: 2,
    colspan: 2,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo6",
  },
  {
    index: 7,
    src: "/images/ptasie/6d.webp",
    title: "stare miasto 2",
    category: "Birds",
    width: 5776,
    height: 4337,
    smcolspan: 7,
    smrowspan: 2,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo7",
  },
  {
    index: 8,
    src: "/images/ptasie/5.webp",
    title: "dogs",
    category: "Birds",
    width: 5776,
    height: 4337,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo8",
  },
  {
    index: 9,
    src: "/images/ptasie/6.webp",
    title: "dogs",
    category: "Birds",
    width: 5184,
    height: 3456,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo9",
  },
  {
    index: 10,
    src: "/images/ptasie/6d2.webp",
    title: "dogs",
    category: "Birds",
    width: 5032,
    height: 3456,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo10",
  },
  {
    index: 11,
    src: "/images/ptasie/finish1.webp",
    title: "dogs",
    category: "Birds",
    width: 5184,
    height: 3791,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo11",
  },
  {
    index: 12,
    src: "/images/ptasie/p1.webp",
    title: "bird-p1",
    category: "Birds",
    width: 5184,
    height: 3791,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2, // Adjusted for aspect ratio
    gridArea: "photo12",
  },
  {
    index: 13,
    src: "/images/s2a.webp",
    title: "staremiasto",
    category: "Murale",
    width: 4336,
    height: 5776,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
  },
  {
    index: 27,
    src: "/images/camper.webp",
    title: "Camper",
    category: "Samochody",
    width: 1914,
    height: 1220,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
  },
  {
    index: 28,
    src: "/images/camper2.webp",
    title: "Camper2",
    category: "Samochody",
    width: 1904,
    height: 1263,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
  },
  {
    index: 28,
    src: "/images/camper3.webp",
    title: "Camper3",
    category: "Samochody",
    width: 5076,
    height: 3368,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
  },
  {
    index: 29,
    src: "/images/c3.webp",
    title: "C3",
    category: "Samochody",
    width: 4032,
    height: 3084,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2, // Adjusted for aspect ratio
  },
];

export const portfolioPhotos = [
  {
    index: 1,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/7b.webp",
    title: "Mural panoramiczny",
    category: "Murale",
    width: 2400,
    height: 426,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 10,
    rowspan: 1,
    gridArea: "photo1",
  },
  {
    index: 2,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/3cropped.webp",
    title: "Mural wielkoformatowy",
    category: "Murale",
    width: 2400,
    height: 888,
    smcolspan: 4,
    smrowspan: 1,
    colspan: 5,
    rowspan: 1,
    gridArea: "photo2",
  },
  {
    index: 3,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/9.webp",
    title: "Mural pionowy",
    category: "Murale",
    width: 1360,
    height: 2400,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 5,
    rowspan: 1,
    gridArea: "photo3",
  },
  {
    index: 4,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/1.webp",
    title: "Mural artystyczny",
    category: "Murale",
    width: 2400,
    height: 1920,
    smcolspan: 4,
    smrowspan: 3,
    colspan: 5,
    rowspan: 2,
    gridArea: "photo4",
  },
  {
    index: 5,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/1c.webp",
    title: "Mural detaliczny",
    category: "Murale",
    width: 1813,
    height: 2400,
    smcolspan: 4,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2,
    gridArea: "photo5",
  },
  {
    index: 6,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/13.webp",
    title: "Mural krajobrazowy",
    category: "Murale",
    width: 2400,
    height: 949,
    smcolspan: 3,
    smrowspan: 2,
    colspan: 2,
    rowspan: 2,
    gridArea: "photo6",
  },
  {
    index: 7,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/4.webp",
    title: "Mural miejski",
    category: "Murale",
    width: 2400,
    height: 500,
    smcolspan: 7,
    smrowspan: 2,
    colspan: 5,
    rowspan: 2,
    gridArea: "photo7",
  },
  {
    index: 8,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/12.webp",
    title: "Mural kolorowy",
    category: "Murale",
    width: 2400,
    height: 1314,
    smcolspan: 10,
    smrowspan: 1,
    colspan: 5,
    rowspan: 2,
    gridArea: "photo8",
  },
  {
    index: 9,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/6.webp",
    title: "Mural dekoracyjny",
    category: "Murale",
    width: 2400,
    height: 2334,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2,
    gridArea: "photo9",
  },
  {
    index: 10,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/8.webp",
    title: "Mural szeroki",
    category: "Murale",
    width: 2400,
    height: 1157,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2,
    gridArea: "photo10",
    objectPosition: "center 35%",
  },
  {
    index: 11,
    src: "/Animation/Murale_Wielkoformatowe/PortfolioCard/4.webp",
    title: "Mural panorama",
    category: "Murale",
    width: 2400,
    height: 500,
    smcolspan: 6,
    smrowspan: 1,
    colspan: 3,
    rowspan: 2,
    gridArea: "photo11",
  },
];

export const komunikacjaWizualnaPhotos = [
  { index: 1, src: "/Animation/Komunikacja_Wizualna/PortfolioCard/przedszkole-1v.webp", title: "Przedszkole", category: "Komunikacja Wizualna", width: 2400, height: 1126, smcolspan: 10, smrowspan: 1, colspan: 10, rowspan: 1, gridArea: "photo1", objectPosition: "center 60%" },
  { index: 2, src: "/Animation/Komunikacja_Wizualna/PortfolioCard/w2.webp", title: "Grafika naścienna", category: "Komunikacja Wizualna", width: 2400, height: 2062, smcolspan: 4, smrowspan: 1, colspan: 5, rowspan: 1, gridArea: "photo2" },
  { index: 3, src: "/Animation/Komunikacja_Wizualna/PortfolioCard/grafika-4.webp", title: "Szyld pionowy", category: "Komunikacja Wizualna", width: 1569, height: 2400, smcolspan: 6, smrowspan: 1, colspan: 5, rowspan: 1, gridArea: "photo3" },
  { index: 4, src: "/Animation/Komunikacja_Wizualna/PortfolioCard/grafika-7.webp", title: "Branding", category: "Komunikacja Wizualna", width: 2400, height: 1577, smcolspan: 4, smrowspan: 3, colspan: 5, rowspan: 2, gridArea: "photo4" },
  { index: 5, src: "/Animation/Komunikacja_Wizualna/PortfolioCard/grafika-6a.webp", title: "Grafika wielkoformatowa", category: "Komunikacja Wizualna", width: 2400, height: 1388, smcolspan: 4, smrowspan: 1, colspan: 5, rowspan: 2, gridArea: "photo5" },
  { index: 6, src: "/Animation/Komunikacja_Wizualna/PortfolioCard/tif-2d.webp", title: "Projekt 2D", category: "Komunikacja Wizualna", width: 2400, height: 1533, smcolspan: 3, smrowspan: 2, colspan: 2, rowspan: 2, gridArea: "photo6" },
  { index: 7, src: "/Animation/Komunikacja_Wizualna/PortfolioCard/grafika-8.webp", title: "Logo", category: "Komunikacja Wizualna", width: 1080, height: 898, smcolspan: 7, smrowspan: 2, colspan: 5, rowspan: 2, gridArea: "photo7" },
];

export const wnetrzaPhotos = [
  { index: 1, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/w1a.webp", title: "Wnętrze panorama", category: "Wnętrza", width: 2400, height: 1168, smcolspan: 10, smrowspan: 1, colspan: 10, rowspan: 1, gridArea: "photo1" },
  { index: 2, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/p1371980.webp", title: "Dekoracja kwadrat", category: "Wnętrza", width: 2400, height: 2400, smcolspan: 4, smrowspan: 1, colspan: 5, rowspan: 1, gridArea: "photo2" },
  { index: 3, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/p1371888.webp", title: "Malowidło ścienne", category: "Wnętrza", width: 1839, height: 2400, smcolspan: 6, smrowspan: 1, colspan: 5, rowspan: 1, gridArea: "photo3" },
  { index: 4, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/w1c.webp", title: "Dekoracja wnętrza", category: "Wnętrza", width: 2400, height: 2312, smcolspan: 4, smrowspan: 3, colspan: 5, rowspan: 2, gridArea: "photo4" },
  { index: 5, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/p1371966.webp", title: "Pokój dziecięcy", category: "Wnętrza", width: 1920, height: 2400, smcolspan: 4, smrowspan: 1, colspan: 5, rowspan: 2, gridArea: "photo5" },
  { index: 6, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/w3.webp", title: "Mural wewnętrzny", category: "Wnętrza", width: 2400, height: 1474, smcolspan: 3, smrowspan: 2, colspan: 2, rowspan: 2, gridArea: "photo6" },
  { index: 7, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/w8.webp", title: "Artystyczne wnętrze", category: "Wnętrza", width: 2400, height: 1713, smcolspan: 7, smrowspan: 2, colspan: 5, rowspan: 2, gridArea: "photo7" },
  { index: 8, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/w11.webp", title: "Dekoracja", category: "Wnętrza", width: 2400, height: 1621, smcolspan: 10, smrowspan: 1, colspan: 5, rowspan: 2, gridArea: "photo8" },
  { index: 9, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/w4a.webp", title: "Pokój portret", category: "Wnętrza", width: 2094, height: 2177, smcolspan: 6, smrowspan: 1, colspan: 3, rowspan: 2, gridArea: "photo9" },
  { index: 10, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/w2.webp", title: "Wnętrze szerokie", category: "Wnętrza", width: 2400, height: 1400, smcolspan: 6, smrowspan: 1, colspan: 3, rowspan: 2, gridArea: "photo10" },
  { index: 11, src: "/Animation/Wnetrza_i_Dekoracje/PortfolioCard/w4.webp", title: "Panorama wnętrza", category: "Wnętrza", width: 2400, height: 1346, smcolspan: 6, smrowspan: 1, colspan: 3, rowspan: 2, gridArea: "photo11" },
];

export const projektySpecjalnePhotos = [
  { index: 1, src: "/Animation/Projekty_Specjalne/PortfolioCard/samochodzik-11.webp", title: "Samochodzik", category: "Projekty Specjalne", width: 2400, height: 1592, gridArea: "photo1", objectPosition: "center 35%" },
  { index: 2, src: "/Animation/Projekty_Specjalne/PortfolioCard/samochodzik-7a.webp", title: "Samochodzik portret", category: "Projekty Specjalne", width: 1916, height: 2400, gridArea: "photo2" },
  { index: 3, src: "/Animation/Projekty_Specjalne/PortfolioCard/samochodzik-10.webp", title: "Malowanie samochodu", category: "Projekty Specjalne", width: 2400, height: 1565, gridArea: "photo3" },
  { index: 4, src: "/Animation/Projekty_Specjalne/PortfolioCard/dscf4057a.webp", title: "Event artystyczny", category: "Projekty Specjalne", width: 2400, height: 1611, gridArea: "photo4" },
  { index: 5, src: "/Animation/Projekty_Specjalne/PortfolioCard/samochodzik-3.webp", title: "Detal samochodu", category: "Projekty Specjalne", width: 2400, height: 1286, gridArea: "photo5" },
  { index: 6, src: "/Animation/Projekty_Specjalne/PortfolioCard/motyl-1a.webp", title: "Motyl mural", category: "Projekty Specjalne", width: 2400, height: 1539, gridArea: "photo6" },
  { index: 7, src: "/Animation/Projekty_Specjalne/PortfolioCard/samochodzik-12.webp", title: "Samochodzik finalny", category: "Projekty Specjalne", width: 2400, height: 1529, gridArea: "photo7" },
];