import React from "react";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import PerformanceMonitor from "./components/PerformanceMonitor";
import { AudioProvider } from "./context/AudioContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

// const interSans = Inter({
//   variable: "--font-inter-sans",
//   subsets: ["latin"],
// });

// const outfit = Outfit({
//   variable: "--font-outfit-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} overflow-y-auto antialiased `}>
        <AudioProvider>
          <PerformanceMonitor />
          <Navbar />
          {children}
          <Footer />
        </AudioProvider>
      </body>
    </html>
  );
}
