import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });


const poppins = Poppins({
  variable: "--font-poppins-sans",
  weight: ['400', '500', '600', '700'], // Add the weights you need
  subsets: ['latin'], // Specify the subsets
});

// const interSans = Inter({
//   variable: "--font-inter-sans",
//   subsets: ["latin"],
// });

// const outfit = Outfit({
//   variable: "--font-outfit-sans",
//   subsets: ["latin"],
// });


// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} overflow-y-auto antialiased `}
      >
        <Navbar />
          {children}
        <Footer />
      </body>
    </html>
  );
}
